confdir = "/etc/confd/mysql"

[template]

src = "/etc/confd/mysql/template/cluster.cnf.tmpl"

dest = "/etc/mysql/conf.d/cluster.cnf"

keys = [ "/services/database" ]

owner = "root"
mode = "0554"

reload_cmd = "mysqladmin shutdown ; mysqld_safe"
